
# _bbparse.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x9d#\x95\xeaaQ\x1e\xd5\x194ld2\x86\x8e\x02'
    
_lr_action_items = {'PYTHON':([0,5,6,9,34,36,37,38,41,43,45,46,],[1,-10,-1,1,-3,-9,-4,-2,-7,-8,-5,-6,]),'VARNAME':([0,1,4,5,6,9,22,34,36,37,38,41,43,45,46,],[2,23,27,-10,-1,2,23,-3,-9,-4,-2,-7,-8,-5,-6,]),'REQUIRE':([0,5,6,9,34,36,37,38,41,43,45,46,],[21,-10,-1,21,-3,-9,-4,-2,-7,-8,-5,-6,]),'NUMBER':([28,32,42,],[53,57,64,]),'INHERITCLASS':([13,39,],[39,39,]),'EXPORT':([0,5,6,9,34,36,37,38,41,43,45,46,],[4,-10,-1,4,-3,-9,-4,-2,-7,-8,-5,-6,]),'INCLUDEFILE':([18,21,],[44,47,]),'APPEND':([2,7,8,14,16,26,27,],[-21,33,-22,-25,-26,-24,-23,]),'COMMENT':([0,5,6,9,34,36,37,38,41,43,45,46,],[5,-10,-1,5,-3,-9,-4,-2,-7,-8,-5,-6,]),'FUNCSTOP':([49,50,66,],[65,-17,-18,]),'INCLUDE':([0,5,6,9,34,36,37,38,41,43,45,46,],[18,-10,-1,18,-3,-9,-4,-2,-7,-8,-5,-6,]),'WEAKASSIGN':([2,7,8,14,16,26,27,],[-21,28,-22,-25,-26,-24,-23,]),'NEWLINE':([0,5,6,8,9,10,11,12,15,17,19,20,24,27,34,36,37,38,39,40,41,43,44,45,46,47,48,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,],[6,-10,-1,34,6,36,37,38,41,43,45,46,-14,-23,-3,-9,-4,-2,-12,-11,-7,-8,-40,-5,-6,-41,-15,-35,-33,-34,-38,-39,-37,-28,-29,-27,-36,-13,-32,-30,-31,-16,]),'FUNCLINE':([25,50,],[50,50,]),'ASSIGN':([2,7,8,14,16,26,27,],[-21,32,-22,-25,-26,-24,-23,]),'$end':([3,5,6,9,34,35,36,37,38,41,43,45,46,],[0,-10,-1,-19,-3,-20,-9,-4,-2,-7,-8,-5,-6,]),'LAZYASSIGN':([2,8,16,27,],[-21,-22,42,-23,]),'STRING':([28,29,30,31,32,33,42,],[52,54,55,56,59,60,63,]),'PREDOT':([2,7,8,14,16,26,27,],[-21,29,-22,-25,-26,-24,-23,]),'INHERIT':([0,5,6,9,34,36,37,38,41,43,45,46,],[13,-10,-1,13,-3,-9,-4,-2,-7,-8,-5,-6,]),'PREPEND':([2,7,8,14,16,26,27,],[-21,31,-22,-25,-26,-24,-23,]),'FLAG':([2,],[26,]),'FUNCSTART':([2,23,],[25,25,]),'POSTDOT':([2,7,8,14,16,26,27,],[-21,30,-22,-25,-26,-24,-23,]),'FAKEROOT':([0,5,6,9,34,36,37,38,41,43,45,46,],[22,-10,-1,22,-3,-9,-4,-2,-7,-8,-5,-6,]),'BOOL':([28,32,42,],[51,58,62,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'func':([0,1,9,22,],[15,24,15,48,]),'func_body':([25,50,],[49,66,]),'assignment':([0,9,],[12,12,]),'require':([0,9,],[19,19,]),'flag':([0,9,],[14,14,]),'inherit':([0,9,],[20,20,]),'syntax':([0,9,],[3,35,]),'export_variable':([0,9,],[8,8,]),'python_func':([0,9,],[10,10,]),'varflag':([0,9,],[7,7,]),'statement':([0,9,],[9,9,]),'variable':([0,9,],[16,16,]),'fakeroot_func':([0,9,],[17,17,]),'include':([0,9,],[11,11,]),'inherit_classes':([13,39,],[40,61,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> syntax","S'",1,None,None,None),
  ('statement -> NEWLINE','statement',1,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',53),
  ('statement -> assignment NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',54),
  ('statement -> export_variable NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',55),
  ('statement -> include NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',56),
  ('statement -> require NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',57),
  ('statement -> inherit NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',58),
  ('statement -> func NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',59),
  ('statement -> fakeroot_func NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',60),
  ('statement -> python_func NEWLINE','statement',2,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',61),
  ('statement -> COMMENT','statement',1,'p_statement','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',62),
  ('inherit -> INHERIT inherit_classes','inherit',2,'p_inherit','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',66),
  ('inherit_classes -> INHERITCLASS','inherit_classes',1,'p_inherit_classes','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',71),
  ('inherit_classes -> INHERITCLASS inherit_classes','inherit_classes',2,'p_inherit_classes','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',72),
  ('python_func -> PYTHON func','python_func',2,'p_python_func','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',77),
  ('fakeroot_func -> FAKEROOT func','fakeroot_func',2,'p_fakeroot_func','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',82),
  ('func -> VARNAME FUNCSTART func_body FUNCSTOP','func',4,'p_func','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',87),
  ('func_body -> FUNCLINE','func_body',1,'p_func_body','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',94),
  ('func_body -> FUNCLINE func_body','func_body',2,'p_func_body','/data/home/oe-lite/bakery/src/oebakery/parse/bbparse.py',95),
  ('syntax -> statement','syntax',1,'p_syntax','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',195),
  ('syntax -> statement syntax','syntax',2,'p_syntax','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',196),
  ('variable -> VARNAME','variable',1,'p_variable','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',209),
  ('variable -> export_variable','variable',1,'p_variable','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',210),
  ('export_variable -> EXPORT VARNAME','export_variable',2,'p_export_variable','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',215),
  ('flag -> VARNAME FLAG','flag',2,'p_flag','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',221),
  ('varflag -> flag','varflag',1,'p_varflag','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',226),
  ('varflag -> variable','varflag',1,'p_varflag','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',227),
  ('assignment -> varflag ASSIGN STRING','assignment',3,'p_simple_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',232),
  ('assignment -> varflag ASSIGN NUMBER','assignment',3,'p_simple_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',233),
  ('assignment -> varflag ASSIGN BOOL','assignment',3,'p_simple_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',234),
  ('assignment -> variable LAZYASSIGN STRING','assignment',3,'p_defaultval_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',239),
  ('assignment -> variable LAZYASSIGN NUMBER','assignment',3,'p_defaultval_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',240),
  ('assignment -> variable LAZYASSIGN BOOL','assignment',3,'p_defaultval_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',241),
  ('assignment -> varflag WEAKASSIGN STRING','assignment',3,'p_weak_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',246),
  ('assignment -> varflag WEAKASSIGN NUMBER','assignment',3,'p_weak_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',247),
  ('assignment -> varflag WEAKASSIGN BOOL','assignment',3,'p_weak_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',248),
  ('assignment -> varflag APPEND STRING','assignment',3,'p_append_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',254),
  ('assignment -> varflag PREPEND STRING','assignment',3,'p_prepend_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',259),
  ('assignment -> varflag PREDOT STRING','assignment',3,'p_predot_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',264),
  ('assignment -> varflag POSTDOT STRING','assignment',3,'p_postdot_assignment','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',269),
  ('include -> INCLUDE INCLUDEFILE','include',2,'p_include','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',274),
  ('require -> REQUIRE INCLUDEFILE','require',2,'p_require','/data/home/oe-lite/bakery/src/oebakery/parse/confparse.py',279),
]
